M48
; DRILL file {KiCad 9.0.1+1} date 2025-11-11T08:29:27+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-11T08:29:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0610
%
G90
G05
T1
X3.9705Y-1.7151
T2
X3.0178Y-1.7151
M30
