M48
; DRILL file {KiCad 9.0.1+dfsg-1} date 2025-05-01T11:00:44+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-01T11:00:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.550
%
G90
G05
T1
X101.212Y-43.894
T2
X77.012Y-43.894
M30
